service:
  name: CloudflareTestVH6
  config:
    accountId: CLOUDFLARE_ACCOUNT_ID
    zoneId: CLOUDFLARE_ZONE_ID
    workers:
      hello:
        routes:
        - k-zhai.com/hello/
      login:
        routes:
        - k-zhai.com/login/

provider:
  name: cloudflare

plugins:
  - serverless-cloudflare-workers

functions:
  cf-handle-hello:
    worker: hello
    script: cf-handle-hello
    events:
      - http:
          url: k-zhai.com/hello/user
          method: GET
          headers:
            Authorization: value
  
  cf-handle-login:
    worker: login
    script: cf-handle-login
    events:
      - http:
          url: k-zhai.com/login/user
          method: POST
          headers:
            username: username
            password: password
